SELECT_ALL_ITEMS = "SELECT * FROM menu_item"
SELECT_ALL_BAKERY = "SELECT * FROM menu_item WHERE tag = 'Bakery';"
SELECT_ALL_BREAKFAST = "SELECT * FROM menu_item WHERE tag = 'Breakfast';"
SELECT_ALL_LUNCH = "SELECT * FROM menu_item WHERE tag = 'Lunch';"
SELECT_ALL_DINNER = "SELECT * FROM menu_item WHERE tag = 'Dinner';"
SELECT_ALL_DESSERT = "SELECT * FROM menu_item WHERE tag = 'Dessert';"
INSERT_MENUITEM_RETURN_ID = "INSERT INTO menu_item (name, description, tag) VALUES (%s, %s, %s) RETURNING id;"
DELETE_MENUITEM_BY_ID = "DELETE FROM menu_item WHERE id = (%s)"
